site_name: Documentation

site_dir: site
site_url: https://example.com
repo_url: https://github.com/yaegashi/azdops-nginx-mkdocs-starter
edit_uri: blob/main/docs

theme:
  name: material
  language: en
  features:
    - navigation.top
    - content.action.edit
    - content.code.copy

plugins:
  - search:
      lang: en
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
